# Generated by Django 5.2.5 on 2025-09-08 12:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_rename_description_review_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review',
            field=models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
    ]
