# Generated by Django 5.2.5 on 2025-10-16 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_rename_date_review_create_at_review_update_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
