# Generated by Django 5.2.5 on 2025-09-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('not_paid', 'not_paid'), ('ready_to_ship', 'ready_to_ship'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('canceled', 'canceled')], default='not_paid'),
        ),
    ]
